baseURL: https://www.cjvillarreal.com/ChrisCodes
languageCode: en-us
title: ChrisCodes 
paginate: 5
theme: "PaperMod"

menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 10
    - identifier: Home
      name: cjvillarreal.com
      url: https://www.cjvillarreal.com/
      weight: 20
      
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai