baseURL: https://www.cjvillarreal.com/ChrisCodes
languageCode: en-us
title: ChrisCodes 
paginate: 5
theme: "PaperMod"

menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 10
    - identifier: Home
      name: cjvillarreal.com
      url: https://www.cjvillarreal.com/
      weight: 20

params:
  assets:
    disableHLJS: false # to disable highlight.js
    disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon.ico"
    favicon32x32: "favicon.ico"
    apple_touch_icon: "favicon.ico"
    safari_pinned_tab: "favicon.ico"      
      
pygmentsUseClasses: true
markup:
  highlight:
    # noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: flase
    # style: monokai
